# NOTE: Generated By RRun v3.1.4
# FROM: testcases\test_letsbim.xlsx


from rrunner import RRun, Config, Step, RunRequest, RunTestCase


class TestCaseTestLetsbim(RRun):

    config = Config("test_letsbim.xlsx").sheetname("accidentRecord")

    teststeps = [
        Step(
            RunRequest("上传文件", 1)
            .with_variables(**{})
            .post("/file")
            .with_json({})
            .upload(
                **{
                    "file": "C:\\Users\\chenjg\\PycharmProjects\\reqponse-master\\file\\小别墅.rvt"
                }
            )
            .extract()
            .validate()
            .assert_equal("body.status", "200")
        ),
    ]


if __name__ == "__main__":
    TestCaseTestLetsbim().test_start()
